version: '3.4'

services:
  app:
    build:
      context: ${APP_BUILD_PATH}
      target: development
    volumes:
      - ./server:/var/www/html
    depends_on:
      - mysql
      - redis
      - s3

  nginx:
    build:
      context: ${NGINX_BUILD_PATH}
      target: development
    ports:
      - ${NGINX_HOST_PORT_HTTP}:${NGINX_CONTAINER_PORT_HTTP}
      - ${NGINX_HOST_PORT_HTTPS}:${NGINX_CONTAINER_PORT_HTTPS}
    volumes:
      - ./infra/nginx/ssl/cert-key.pem:/etc/nginx/certs/cert-key.pem
      - ./infra/nginx/ssl/cert.pem:/etc/nginx/certs/cert.pem
      - ./server/public:/var/www/html/public
      - ./server/storage/app/public:/var/www/html/public/storage
    depends_on:
      - app

  mysql:
    # platform: linux/x86_64
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}

  s3:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: bash
    command: -c "/usr/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
      - ./infra/s3/data:/export
    ports:
      - '9000:9999'
      - '9001:9001'

  redis:
    image: redis:7.2.3-alpine
    ports:
      - '63790:6379'
    volumes:
      - ./infra/redis/data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - '18081:8081'
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379

  # 開発環境のメール送信検証用
  # URL: http://localhost:8025
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
